name: ips_typographus
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  # Bioinformatics tools
  - ipyrad=0.9.95
  - baypass=2.41
  - plink=1.90b6.21
  - vcftools=0.1.16
  - liftoff=1.6.3
  
  # Python
  - python=3.10
  - numpy=2.1.3
  - pandas=2.1.4
  - scipy=1.10.0
  - scikit-learn=1.5.2
  - matplotlib=3.8.0
  - seaborn=0.13.0
  - cyvcf2=0.30.15
  - joblib=1.4.2
  
  # LightGBM and optimization
  - lightgbm=4.5.0
  - optuna=4.2.0
  
  # R and Bioconductor
  - r-base=4.4.2
  - r-tidyverse=2.0.0
  - r-ggplot2=3.4.4
  - r-dplyr=1.1.4
  - r-tidyr=1.3.1
  - r-stringr=1.5.1
  - r-gridExtra=2.3
  - bioconductor-adegenet=2.1.10
  - bioconductor-rrblup=4.6.3
  - bioconductor-vcfr=1.14.0
  - bioconductor-goseq=1.54.0
  - bioconductor-genomicranges=1.54.0
  - bioconductor-genomicfeatures=1.54.0
  
  # Visualization
  - r-gplots=3.1.3
  - r-igraph=2.1.1
  - r-plotly=4.10.2
  
  # Utilities
  - git=2.45.2
  - perl-math-cdf=0.1

pip:
  - pandas>=2.1.4
  - numpy>=2.1.3
  - scipy>=1.10.0
  - scikit-learn>=1.5.2
  - lightgbm>=4.5.0
  - optuna>=4.2.0
  - matplotlib>=3.8.0
  - seaborn>=0.13.0
  - cyvcf2>=0.30.15
  - joblib>=1.4.2
